# Generated by Django 4.2.1 on 2024-08-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('logo', models.FileField(upload_to='')),
                ('type_of_event', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='signup_model',
        ),
    ]
