# Generated by Django 4.2.1 on 2024-08-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_event_model_delete_signup_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_model',
            name='logo',
        ),
        migrations.AddField(
            model_name='event_model',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
